xxl-job-admin:
  image:
    repository: minixxie/xxl-job-admin
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "2.3.1"
  mysql:
    host: mysql.infra-mysql.svc
    port: 3306
    user: xxl_job
    password: xxl_job
    database: xxl_job
  initDB:
    enabled: false
    image:
      registry: library/mysql
      tag: "8.2.0"
  ingress:
    enabled: true
    hosts:
      - host: xxljob.local
        paths:
          - path: /
            pathType: ImplementationSpecific
  properties:
    server:
      port: 8080
      servlet:
        context-path: /
